Semantic/InterfaceWeb/src/eventController/CreateEventController.java
package eventController;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import service.EventService;
import service.Service;
import service.bean.EventBean;
import service.bean.FileBean;
import service.bean.PersonBean;
import service.bean.StatementBean;
import service.bean.factory.FactoryEventBean;
import util.exception.BusinessException;
import controllerAbstract.ControllerAbstract;
import eventController.helper.ManagerDBPedia;
import eventController.helper.ManagerFileUpload;
import eventController.helper.ManagerParticipant;

@ManagedBean
@ViewScoped
public class CreateEventController extends ControllerAbstract {

	@ManagedProperty(value = "#{managerFileUpload}")
	private ManagerFileUpload managerFileUpload;

	@ManagedProperty(value = "#{managerParticipant}")
	private ManagerParticipant managerParticipant;

	@ManagedProperty(value = "#{managerDBPedia}")
	private ManagerDBPedia managerDBPedia;

	private EventService eventService = new EventService();
	private EventBean event;
	private FactoryEventBean fEventBean = new FactoryEventBean();

	public boolean isEventEdit() {

		return this.getSessionMap().existEventEdit();
	}

	@PostConstruct
	public void init() {

		try {

			Service.startUseCase();

			if (isEventEdit() == true) {

				String uriEdit = this.getSessionMap().getEventEdit();

				this.event = this.eventService.findEventByURI(uriEdit);

				this.managerFileUpload.addAllFiles(this.event.getFileBeans());

				this.managerParticipant
						.addAllParticipant(this.event.getParticipants());

				this.managerDBPedia.addAllStatementBean(this.event
						.getElementsDBpedia());
				
			}else{
				
				this.event = fEventBean.createEmpityEventBean();
			}

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);
		}
	}

	public EventBean getEvent() {
		return event;
	}


	public List<FileBean> getListFileUpload() {

		return this.managerFileUpload.getList();
	}

	public void setRemoveListFileUpload(FileBean fileBean) {

		this.managerFileUpload.removeFile(fileBean.getName());
	}

	public ManagerParticipant getManagerParticipant() {

		return this.managerParticipant;
	}

	public ManagerDBPedia getManagerDBPedia() {

		return this.managerDBPedia;
	}

	public void findDBpedia() {

		this.managerDBPedia.setWords(this.event.getDescripition());
		this.managerDBPedia.findWords();

	}

	public void save() {

		try {

			//era iniciado outro caso de uso aqui
//			this.newEventService();
			
			this.event.removeAllFileBeans();
			this.event.removeAllParticipants();
			this.event.removeAllElementDBpedia();

			for (FileBean f : this.managerFileUpload.getList()) {

				this.event.addFileBeans(f);
			}

			for (PersonBean p : this.managerParticipant.getParticipants()) {

				this.event.addParticipant(p);
			}

			for (StatementBean s : this.managerDBPedia.getList()) {

				this.event.addElementDBpedia(s);
			}

			this.event.setNickNameOwnerOfEvent(this.getSessionMap().getUserNickNameSession());			

			if (this.isEventEdit() == true) {
				
				this.eventService.update(event);

			}else{

				this.eventService.insert(this.event);
			}
			
			this.getSessionMap().putNullEventEdit();
			
			this.getDefaultRedirect().redirectPageViewEvent();

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);
		}
	}

	public void cancel() {
		
		this.getSessionMap().putNullEventEdit();
		
		this.getDefaultRedirect().redirectPageViewEvent();
	}


	

	public ManagerFileUpload getManagerFileUpload() {
		return managerFileUpload;
	}

	public void setManagerFileUpload(ManagerFileUpload managerFileUpload) {
		this.managerFileUpload = managerFileUpload;
	}

	public void setManagerParticipant(ManagerParticipant managerParticipant) {
		this.managerParticipant = managerParticipant;
	}

	public void setManagerDBPedia(ManagerDBPedia managerDBPedia) {
		this.managerDBPedia = managerDBPedia;
	}
	
}

Semantic/InterfaceWeb/src/eventController/FindEventByParticipantController.java
package eventController;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import service.Service;
import controllerAbstract.ControllerAbstract;
import eventController.helper.ManagerParticipant;

@ManagedBean
@ViewScoped
public class FindEventByParticipantController extends ControllerAbstract{
	
	@ManagedProperty(value = "#{managerParticipant}")
	private ManagerParticipant managerParticipant;	
	
	@PostConstruct
	public void init() {
		
		Service.startUseCase();

	}
	

	public ManagerParticipant getManagerParticipant() {
		return managerParticipant;
	}

	public void setManagerParticipant(ManagerParticipant managerParticipant) {
		this.managerParticipant = managerParticipant;
	}
	
	
	public void findEvents(){		
		
		this.getSessionMap().putParticipantsOfEvent(this.managerParticipant.getParticipants());
		
		this.getDefaultRedirect().redirectPageViewEvent();
	}

}

Semantic/InterfaceWeb/src/eventController/ViewEventController.java
package eventController;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.primefaces.event.NodeSelectEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.TreeNode;

import service.EventService;
import service.Service;
import service.bean.EventBean;
import service.bean.PersonBean;
import util.exception.BusinessException;
import controllerAbstract.ControllerAbstract;
import eventController.helper.EventTreeNodeHelper;
import eventController.helper.ManagerFile;

@ManagedBean
@ViewScoped
public class ViewEventController extends ControllerAbstract implements
		Serializable {

	private static final long serialVersionUID = 8747242186453494614L;

	@ManagedProperty("#{eventTreeNodeHelper}")
	private EventTreeNodeHelper eventTreeNodeHelper;
	@ManagedProperty("#{managerFile}")
	private ManagerFile managerFile;
	private EventService eventService = new EventService();

	private TreeNode root;
	private List<String> images;

	private EventBean event;
	private boolean rendered = true;
	private boolean disabled = false;

	@PostConstruct
	public void init() {

		Service.startUseCase();
		
		try {

			this.root = this.eventTreeNodeHelper.createDefaultTreeNode();

			if (this.getSessionMap().existParticipantsOfEvent()
					&& this.getSessionMap().existUser()) {

				this.initByFindEventParticipant();

			} else {

				if (this.getSessionMap().existDates()
						&& this.getSessionMap().existUser()) {

					this.initByDate();

				} else {

					if (this.getSessionMap().existEventURI() == false
							&& this.getSessionMap().existUser()) {

						this.initByEventRoot();

					} else {

						this.initByURIDereferencie();
					}

				}
			}

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);
		}
	}

	private void initByFindEventParticipant() throws BusinessException {

		List<PersonBean> personBeans = this.getSessionMap()
				.getParticipantsOfEvent();

		List<String> uris = new ArrayList<String>();

		for (PersonBean p : personBeans) {

			uris.add(p.getUri());
		}

		List<EventBean> eventBeans = this.eventService
				.findEventByParticipant(uris, this.getSessionMap().getUserNickNameSession());

		this.eventTreeNodeHelper.recursiveSearchForSubEvents(this.root,
				eventBeans);

		this.getSessionMap().putNullParticipantsOfEvent();
	}

	private void initByURIDereferencie() throws BusinessException {

		EventBean eventBean = this.eventService.findEventByURI(this
				.getSessionMap().getEventURI());

		List<EventBean> list = new ArrayList<EventBean>();
		list.add(eventBean);

		this.eventTreeNodeHelper.recursiveSearchForSubEvents(this.root, list);

		this.getSessionMap().putNullEventURI();
		this.disabled = true;

	}

	private void initByEventRoot() throws BusinessException {

		List<EventBean> eventBeans = this.eventService
				.findEventsRootByNickName(this.getSessionMap()
						.getUserNickNameSession());

		this.eventTreeNodeHelper.recursiveSearchForSubEvents(this.root,
				eventBeans);

		this.getSessionMap().putFalseDereference();

	}

	private void initByDate() throws BusinessException {

		Date date1 = this.getSessionMap().getDate1();
		Date date2 = this.getSessionMap().getDate2();

		for (EventBean e : eventService.findEventByDate(date1, date2, this
				.getSessionMap().getUserNickNameSession())) {

			List<EventBean> list = new ArrayList<EventBean>();
			list.add(e);

			this.eventTreeNodeHelper.recursiveSearchForSubEvents(this.root,
					list);

		}

		this.getSessionMap().putDate1Null();
		this.getSessionMap().putDate2Null();
		this.getSessionMap().putFalseDereference();

	}

	public TreeNode getRoot() {

		return root;
	}

	public void onEventSelect(NodeSelectEvent event) {

		try {
			
			Service.startUseCase();
			
			this.managerFile.clear();

			// Só tinha serventia quando era para não aparecer as informações no
			// inicio. Elas só apareceiam depois que clicava.
			this.rendered = true;

			EventBean ev = (EventBean) event.getTreeNode().getData();

			this.event = this.eventService.findEventByURI(ev.getUri());

			this.managerFile.saveFileInServer(this.event.getFileBeans());

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);
		}

	}

	public void onOwner() {

		this.getSessionMap().putPersonNickName(
				this.event.getNickNameOwnerOfEvent());
		this.getDefaultRedirect().redirectPageViewPerson();
	}

	public void onParticipant(SelectEvent event) {

		this.getSessionMap().putPersonNickName(
				((PersonBean) event.getObject()).getNickName());
		this.getDefaultRedirect().redirectPageViewPerson();
	}

	public EventBean getEvent() {
		return event;
	}

	public List<String> getImages() {
		return images;
	}

	public boolean isRendered() {
		return rendered;
	}

	public void setEventRemove(EventBean eventBean) {

		try {

			Service.startUseCase();
			
			this.eventService.remove(eventBean.getUri());

			this.getDefaultRedirect().redirectPageViewEvent();

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);
		}
	}

	public void setEventEdit(EventBean eventBean) {

		this.getSessionMap().putEventEdit(eventBean.getUri());

		this.getDefaultRedirect().redirectPageEditAndCreateEvent();
	}

	public boolean isDisabled() {
		return disabled;
	}

	public void setEventTreeNodeHelper(EventTreeNodeHelper eventTreeNodeHelper) {
		this.eventTreeNodeHelper = eventTreeNodeHelper;
	}

	public ManagerFile getManagerFile() {
		return managerFile;
	}

	public void setManagerFile(ManagerFile managerFile) {
		this.managerFile = managerFile;
	}

}

Semantic/InterfaceWeb/src/login/LoginController.java
package login;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import service.PersonService;
import service.Service;
import util.exception.BusinessException;
import controllerAbstract.ControllerAbstract;

@ManagedBean
@ViewScoped
public class LoginController extends ControllerAbstract {

	private String nickName;
	private String password;

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void logout() {

		if (this.getSessionMap().existUser()) {

			FacesContext.getCurrentInstance().getExternalContext()
					.getSession(false);
			FacesContext.getCurrentInstance().getExternalContext()
					.invalidateSession();
			
			this.getSessionMap().putNullUserNickNameSession();

			this.getDefaultRedirect().redirectPageInitial();
			
		}else{
			
			this.getDefaultRedirect().redirectPageLogin();
		}

	}

	public void login() {
		
		Service.startUseCase();
		
		PersonService personService = new PersonService();

		try {

			boolean result = personService.existThatPersonInDataBase(this.getNickName(), this.getPassword());
			
			if (result == true) {
								
				this.getSessionMap().putUserNickNameSession(this.getNickName());
				
				this.getDefaultRedirect().redirectPageHome();

			} else {
				
				this.getMessage().addMessageErro("The username or password are incorrect!");

			}

		} catch (BusinessException e) {
			
			this.getMessage().addMessagesBusinessException(e);

		}
	}

}

Semantic/InterfaceWeb/src/personController/CreatePersonController.java
package personController;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import service.PersonService;
import service.Service;
import service.bean.PersonBean;
import service.bean.factory.FactoryPersonBean;
import util.exception.BusinessException;
import controllerAbstract.ControllerAbstract;

@ManagedBean
@ViewScoped
public class CreatePersonController extends ControllerAbstract{
	
	private PersonBean personBean;
	private PersonService personService = new PersonService();
	
	@PostConstruct
	private void init(){
		
		Service.startUseCase();
		
		this.personBean = new FactoryPersonBean().createPersonBeanEmpity();		
	}

		
	
    public void confirm() {
    	
    	try {
	    		
    		this.personService.insert(this.personBean);
    		
    		this.getDefaultRedirect().redirectPageLogin();
    		
    	} catch (BusinessException e) {
    		
    		this.getMessage().addMessagesBusinessException(e);
			
		}
    }
	

	public PersonBean getPersonBean() {
		
		return personBean;
	}

	public void setPersonBean(PersonBean personBean) {
		
		this.personBean = personBean;
	}
	
}

Semantic/InterfaceWeb/src/personController/FindPersonController.java
package personController;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.primefaces.event.SelectEvent;

import controllerAbstract.ControllerAbstract;
import service.Service;
import service.bean.PersonBean;
import eventController.helper.ManagerParticipant;

@ManagedBean
@ViewScoped
public class FindPersonController extends ControllerAbstract{
	
	@ManagedProperty(value = "#{managerParticipant}")
	private ManagerParticipant managerParticipant;

	@PostConstruct
	public void init() {
		
		Service.startUseCase();
	}

	
	public ManagerParticipant getManagerParticipant() {
		return managerParticipant;
	}

	public void setManagerParticipant(ManagerParticipant managerParticipant) {
		this.managerParticipant = managerParticipant;
	}
	
	public void onParticipant(SelectEvent event) {

		this.getSessionMap().putPersonNickName(
				((PersonBean) event.getObject()).getNickName());
		this.getDefaultRedirect().redirectPageViewPerson();
	}



}

Semantic/InterfaceWeb/src/personController/UpdatePersonController.java
package personController;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import service.PersonService;
import service.Service;
import service.bean.PersonBean;
import util.exception.BusinessException;
import controllerAbstract.ControllerAbstract;

@ManagedBean
@ViewScoped
public class UpdatePersonController extends ControllerAbstract {

	private PersonBean personBean;

	private PersonService personService = new PersonService();

	@PostConstruct
	private void init() {

		Service.startUseCase();
		
		try {

			String nickName = this.getSessionMap().getUserNickNameSession();

			this.setPersonBean(this.personService
					.findPersonByNickName(nickName));

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);

		}

	}

	public void salvar() {

		try {

			this.personService.update(this.personBean);

			this.getDefaultRedirect().redirectPageViewPerson();

		} catch (BusinessException e) {

			this.getMessage().addMessagesBusinessException(e);

		}

	}

	public void cancelar() {

		this.getDefaultRedirect().redirectPageViewPerson();
	}

	public PersonBean getPersonBean() {
		return personBean;
	}

	public void setPersonBean(PersonBean personBean) {
		this.personBean = personBean;
	}

}

Semantic/InterfaceWeb/src/telaPrincipalController/TelaPrincipalController.java
package telaPrincipalController;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;

import controllerAbstract.ControllerAbstract;

@ManagedBean
@SessionScoped
public class TelaPrincipalController extends ControllerAbstract {

	public void login(ActionEvent actionEvent) {

		this.getDefaultRedirect().redirectPageLogin();

	}

	public void cadastrarUsuario(ActionEvent actionEvent) {

		this.getDefaultRedirect().redirectPageCreatePerson();

	}

}

Semantic/InterfaceWeb/WebContent/createEvent.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadraoIn.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo"> Event Information </ui:define>

	<ui:define name="corpo">
		<br />

		<p:growl id="messages" showSummary="true" showDetail="false"
			autoUpdate="true" />

		<h:form id="form1">


			<p:panelGrid columns="2" style="margin-top:20px">
				<f:facet name="header">
					<p:row>
 			           <p:column colspan="7">Register Event</p:column>
			        </p:row>
				</f:facet>

				<p:outputLabel value="NickFather:" for="nickFather" />
				<p:inputText id="nickFather"
					value="#{createEventController.event.eventFather.nick}"/>


				<p:outputLabel value="Name:" for="name" />
				<p:inputText id="name" value="#{createEventController.event.name}"
					required="true" />

				<p:outputLabel value="Nick:" for="nick" />
				<p:inputText id="nick" value="#{createEventController.event.nick}"
					required="true" disabled="#{createEventController.eventEdit}" />


				<p:outputLabel value="Date:" for="date" />
				<p:calendar id="date" value="#{createEventController.event.date}"
					pattern="dd/MM/yyyy" mask="true" required="true"
					requiredMessage="Date: Required field"
					converterMessage="The date entered does not exist !! Please enter a valid date EX: 14/01/1994" />

				<p:outputLabel value="Description:" for="description" />
				<p:inputTextarea id="description" rows="6" cols="33"
					value="#{createEventController.event.descripition}" />


				<p:outputLabel value="Latitude:" for="latitude" />
				<p:inputText id="latitude"
					value="#{createEventController.event.latitude}" />

				<p:outputLabel value="Longitude:" for="longitude" />
				<p:inputText id="longitude"
					value="#{createEventController.event.longitude}" />

				<p:outputLabel value="File:" for="panelGridFileUpload" />

				<h:panelGrid id="panelGridFileUpload" columns="1">

					<p:fileUpload
						fileUploadListener="#{createEventController.managerFileUpload.handleFileUpload}"
						mode="advanced" dragDropSupport="false" auto="true"
						allowTypes="/(\.|\/)(gif|jpe?g|png)$/" skinSimple="true" />
					
					<p:outputLabel value="File Name:" for="fileName" />
						
					<p:inputText id="fileName"
						value="#{createEventController.managerFileUpload.nameFile}" />

					<p:commandButton value="Add File"
						update=":form1:dataTableFile"
						action="#{createEventController.managerFileUpload.addFile}" />
						

					<p:dataTable id="dataTableFile" var="file"
						value="#{createEventController.listFileUpload}"
						style="width:400px">

						<p:column headerText="File Name">
							<h:outputText value="#{file.name}" />
						</p:column>

						<p:column headerText="Remove" style="width:50px">
							<p:commandLink update=":form1:dataTableFile" title="Remove Event"
								styleClass="ui-icon ui-icon-close">
								<f:setPropertyActionListener value="#{file}"
									target="#{createEventController.removeListFileUpload}"/>
							</p:commandLink>
						</p:column>
					</p:dataTable>
				</h:panelGrid>




				<p:outputLabel value="Find Participants: " />

				<h:panelGrid columns="3">

					<p:outputLabel value="Name of Person:" for="nickNamePerson" />

					<p:inputText id="nickNamePerson"
						value="#{createEventController.managerParticipant.nameFind}" />

					<p:commandButton value="search"
						update=":form1:dataTableParticipant"
						action="#{createEventController.managerParticipant.findParticipant}" />

				</h:panelGrid>


				<p:outputLabel value="Participants: " />

				<h:panelGrid columns="1">


					<p:dataTable id="dataTableParticipant" var="participant"
						value="#{createEventController.managerParticipant.participantFinds}"
						style="width:400px">

						<f:facet name="header">
						Search Result of Participants
						</f:facet>


						<p:column headerText="Name">
							<h:outputText value="#{participant.name}" />
						</p:column>

						<p:column headerText="Add" style="width:60px">
							<p:commandLink update=":form1:dataTableParticipant2"
								title="Adicionar" styleClass="ui-icon ui-icon-plus">
								<f:setPropertyActionListener value="#{participant}"
									target="#{createEventController.managerParticipant.addParticipant}" />
							</p:commandLink>
						</p:column>
					</p:dataTable>



					<p:dataTable id="dataTableParticipant2" var="participant"
						value="#{createEventController.managerParticipant.participants}"
						style="width:400px">

						<f:facet name="header">
						Participants Added
						</f:facet>


						<p:column headerText="Name">
							<h:outputText value="#{participant.name}" />
						</p:column>

						<p:column headerText="Remove" style="width:50px">
							<p:commandLink update=":form1:dataTableParticipant2"
								title="Remover" styleClass="ui-icon ui-icon-close">
								<f:setPropertyActionListener value="#{participant}"
									target="#{createEventController.managerParticipant.removeParticipant}" />
							</p:commandLink>
						</p:column>
					</p:dataTable>

				</h:panelGrid>


				<p:outputLabel value="DBpedia: " />

				<h:panelGrid columns="1">

					<p:commandButton value="Search in DBpedia"
						update=":form1:dataTableDBpedia"
						action="#{createEventController.findDBpedia}" />

					<p:dataTable id="dataTableDBpedia" var="statement"
						value="#{createEventController.managerDBPedia.statementBeanFind}"
						style="width:800px">

						<f:facet name="header">
						Search Result of DBpedia
						</f:facet>

						<p:column headerText="Label" style="width:300px">
							<h:outputLink value="#{statement.uri}">
								<h:outputText value="#{statement.label}" />
							</h:outputLink>
						</p:column>

						<p:column headerText="Comment" style="width:300px">
							<h:outputText value="#{statement.comment}" />
						</p:column>

						<p:column headerText="Add" style="width:100px">
							<p:commandLink update=":form1:dataTableDBpedia2"
								title="Adicionar" styleClass="ui-icon ui-icon-plus">
								<f:setPropertyActionListener value="#{statement}"
									target="#{createEventController.managerDBPedia.addStatementBean}" />
							</p:commandLink>
						</p:column>
					</p:dataTable>



					<p:dataTable id="dataTableDBpedia2" var="statement"
						value="#{createEventController.managerDBPedia.list}" style="width:800px">

						<f:facet name="header">
						DBpedia Elements Added
						</f:facet>


						<p:column headerText="Label" style="width:300px">
							<h:outputLink value="#{statement.uri}">
								<h:outputText value="#{statement.label}" />
							</h:outputLink>
						</p:column>

						<p:column headerText="Comment" style="width:300px">
							<h:outputText value="#{statement.comment}" />
						</p:column>


						<p:column headerText="Remove" style="width:100px">
							<p:commandLink update=":form1:dataTableDBpedia2" title="Remover"
								styleClass="ui-icon ui-icon-close">
								<f:setPropertyActionListener value="#{statement}"
									target="#{createEventController.managerDBPedia.removeStatementBean}" />
							</p:commandLink>
						</p:column>
					</p:dataTable>
				</h:panelGrid>





				<f:facet name="footer">
					<h:panelGroup layout="block"
						style="text-align:right; padding:2px; white-space:nowrap;">
						<p:commandButton value="Save" update=":messages"
							action="#{createEventController.save}" />

						<p:commandButton value="Close"
							action="#{createEventController.cancel}" immediate="true" />
					</h:panelGroup>
				</f:facet>


			</p:panelGrid>
		</h:form>


		<br />
	</ui:define>

</ui:composition>

Semantic/InterfaceWeb/WebContent/createPerson.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadraoOut.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Register for User</ui:define>

	<ui:define name="corpo">
		<br />

		<h:form>

			<p:messages id="messages" />

			<p:panelGrid columns="2">
				<f:facet name="header">
					Register User
				</f:facet>


				<p:outputLabel value="Name:" for="name" />
				<p:inputText id="name" value="#{createPersonController.personBean.name}"
					required="true" requiredMessage="Name: Campo obrigatorio" />
					
				<p:outputLabel value="NickName:" for="nickName" />
				<p:inputText id="nickName" value="#{createPersonController.personBean.nickName}"
					required="true" requiredMessage="NickName: Campo obrigatorio" />
					

				<p:outputLabel value="E-mail:" for="email" />
				<p:inputText id="email" value="#{createPersonController.personBean.email}"
					required="true" requiredMessage="Email: Campo obrigatorio"
					validatorMessage="O email informado não esta correto!!">

					<f:validateRegex
						pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />

				</p:inputText>

				<p:outputLabel for="pwd1" value="Password:" />
				<p:password id="pwd1" value="#{createPersonController.personBean.password}"
					match="pwd2" label="Password 1" required="true"
					requiredMessage="Password 1: Campo obrigatorio"
					validatorMessage="Password 1 e Password 2 não são iguais. Por favor digite a senha novamente !!" />

				<p:outputLabel for="pwd2" value="Confirm the password:" />
				<p:password id="pwd2" value="#{createPersonController.personBean.password}"
					label="Password 2" required="true"
					requiredMessage="Confirm the password: Campo obrigatorio" />


				<f:facet name="footer">
					<p:commandButton value="Register" action="#{createPersonController.confirm}"
						update="messages" />
				</f:facet>

			</p:panelGrid>

		</h:form>

		<br />
	</ui:define>

</ui:composition>

Semantic/InterfaceWeb/WebContent/home.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadraoIn.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Home</ui:define>

	<ui:define name="corpo">
		<br />
		<br />
		<br />
		
		
		<h3>Welcome to implementing the final project 2!</h3>
		
		<br />
		<br />
		<br />
	</ui:define>

</ui:composition>